"""
Load validation outputs for exception diagnosis.
"""

import json
from pathlib import Path
from typing import Any
import pandas as pd

from .config import (
    MISSING_FIELD_REPORT,
    DEAL_STATUS_REPORT,
    PDF_SURVEY_REPORT,
    PDF_VALIDATION_SEARCH_ROOTS,
    BATCH_SUMMARY_REPORT,
)

from .adapters.pdf_validation_adapter import (
    load_pdf_validation_issues,
    build_batch_blocked_issues,
)


def load_csv(path: Path) -> pd.DataFrame:
    """
    Generic CSV loader.
    Returns empty dataframe if file does not exist.
    """

    if not path.exists():
        return pd.DataFrame()

    return pd.read_csv(path)


def load_missing_fields() -> pd.DataFrame:
    """
    Load missing field validation results.
    """

    return load_csv(MISSING_FIELD_REPORT)


def load_deal_status() -> pd.DataFrame:
    """
    Load deal status validation results.
    """

    return load_csv(DEAL_STATUS_REPORT)


def load_pdf_survey() -> pd.DataFrame:
    """
    Load PDF validation survey results.

    This contains document-level information:
    - extraction mode
    - comparability
    - blocked reasons
    """

    return load_csv(PDF_SURVEY_REPORT)


def load_pdf_batch_summary():

    if not BATCH_SUMMARY_REPORT.exists():
        return []

    import json

    with BATCH_SUMMARY_REPORT.open(
        encoding="utf-8"
    ) as f:
        summary = json.load(f)

    return summary.get("results", [])


def find_pdf_validation_outputs():
    """
    Find all vendor_comparison output folders
    generated by PDF validation pipeline.
    """

    vendor_dirs = []

    for root in PDF_VALIDATION_SEARCH_ROOTS:

        if not root.exists():
            continue

        for name in ["vendor_comparison", "compare"]:
            vendor_dirs.extend(
                [
                    path
                    for path in root.rglob(name)
                    if path.is_dir()
                    and (path / "comparison_report.json").exists()
                ]
            )

    return vendor_dirs


def load_pdf_metadata(vendor_dir: Path):
    """
    Load fund metadata from PDF comparison report.

    Returns:
        fund_id,
        as_at_date
    """

    report_path = vendor_dir / "comparison_report.json"

    if not report_path.exists():
        return None, None

    with report_path.open(
        encoding="utf-8"
    ) as f:
        report = json.load(f)

    summary = report.get("summary", {})

    return (
        summary.get("vendor_fund_id"),
        summary.get("pdf_as_of_date"),
    )

def load_pdf_validation_outputs() -> list:

    issues = []

    issues.extend(
        build_batch_blocked_issues(
            load_pdf_batch_summary()
        )
    )

    for vendor_dir in find_pdf_validation_outputs():

        fund_id, as_at_date = load_pdf_metadata(
            vendor_dir
        )

        issues.extend(
            load_pdf_validation_issues(
                vendor_dir,
                fund_id=fund_id,
                as_at_date=as_at_date,
            )
        )

    return issues


def load_all_validation_outputs() -> dict[str, Any]:
    """
    Load all available validation outputs.
    """

    return {
        "missing_fields": load_missing_fields(),
        "deal_status": load_deal_status(),
        "pdf_survey": load_pdf_survey(),
        "pdf_validation": load_pdf_validation_outputs(),
    }