"""
Generate Office-facing Phase 1 Data-State Analysis summaries.

This module ONLY adapts existing Phase 1 outputs
into presentation-ready summaries.

It does NOT:
- load raw holdings data
- recompute Phase 1 metrics
- perform quality analysis

All analytical results are generated upstream
and stored under reports/.

"""

from pathlib import Path
import re
import pandas as pd


def _load_csv(path: Path):

    """
    Safely load existing Phase 1 outputs.
    """

    if not path.exists():
        return None

    return pd.read_csv(path)


def _format_percent(value):

    if pd.isna(value):
        return ""

    return f"{float(value):.1%}"


def _load_phase1_headline(
    reports_dir: Path
):
    """
    Read Phase 1 headline metrics
    documented in README_reports_guide.md.

    These values are generated by Phase 1
    and should not be recomputed here.
    """

    readme = (
        reports_dir
        /
        "README_reports_guide.md"
    )

    if not readme.exists():
        return {}

    text = readme.read_text(
        encoding="utf-8"
    )

    result = {}


    # Completeness headline
    completeness_match = re.search(
        r"unconditional fill rate\s+([0-9.]+)%\s*→\s*conditional completeness\s+([0-9.]+)%",
        text,
        flags=re.IGNORECASE
    )

    if completeness_match:

        unconditional = (
            completeness_match.group(1)
            +
            "%"
        )

        conditional = (
            completeness_match.group(2)
            +
            "%"
        )

        result["Unconditional Completeness"] = unconditional

        result["Conditional Completeness"] = conditional

        try:

            delta = (
                float(
                    completeness_match.group(2)
                )
                -
                float(
                    completeness_match.group(1)
                )
            )

            result[
                "Conditional Improvement"
            ] = f"+{delta:.1f}%"

        except Exception:

            pass


    # Fund quality headline
    fund_match = re.search(
        r"below\s+the\s+85%\s+threshold\s+drop\s+from\s+(\d+)\s+to\s+(\d+)",
        text,
        flags=re.IGNORECASE | re.DOTALL
    )

    if fund_match:

        result[
            "Funds Below 85% Unconditional"
        ] = int(
            fund_match.group(1)
        )

        result[
            "Funds Below 85% Conditional"
        ] = int(
            fund_match.group(2)
        )

    return result


def get_phase1_summary(
    reports_dir: Path,
):

    """
    Convert existing Phase 1 outputs
    into executive reporting metrics.
    """

    summary = {}

    # 1. Coverage Overview
    fund_df = _load_csv(
        reports_dir /
        "data_state_by_fund.csv"
    )

    manager_df = _load_csv(
        reports_dir /
        "data_state_by_manager.csv"
    )

    coverage = {}

    if fund_df is not None:

        coverage[
            "Funds Covered"
        ] = len(fund_df)

    if manager_df is not None:

        coverage[
            "Managers Covered"
        ] = len(manager_df)

        if "n_rows" in manager_df.columns:

            coverage[
                "Investment Rows Analyzed"
            ] = int(
                manager_df[
                    "n_rows"
                ].sum()
            )

    summary["coverage"] = coverage


    # 2. Completeness Assessment
    headline = _load_phase1_headline(
        reports_dir
    )

    completeness = {}

    if "Unconditional Completeness" in headline:

        completeness[
            "Unconditional Completeness"
        ] = headline[
            "Unconditional Completeness"
        ]

    if "Conditional Completeness" in headline:

        completeness[
            "Conditional Completeness"
        ] = headline[
            "Conditional Completeness"
        ]

    if "Conditional Improvement" in headline:

        completeness[
            "Conditional Improvement"
        ] = headline[
            "Conditional Improvement"
        ]

    summary["completeness"] = completeness


    # 3. Conditional Missing Field Patterns
    missing_df = _load_csv(
        reports_dir /
        "flagged_missing_fields_conditional.csv"
    )

    field_quality = []

    if missing_df is not None:

        if (
            "missing_expected_fields"
            in missing_df.columns
        ):

            missing_fields = (
                missing_df[
                    "missing_expected_fields"
                ]
                .dropna()
                .str.split(",")
                .explode()
                .str.strip()
            )

            counts = (
                missing_fields
                .value_counts()
                .head(5)
            )

            for field, count in counts.items():

                field_quality.append(
                    {
                        "Field":
                            field,

                        "Missing Records":
                            int(count)
                    }
                )

    summary[
        "field_quality"
    ] = field_quality


    # 4. Fund Quality
    fund_quality = {}

    if (
        "Funds Below 85% Unconditional"
        in headline
    ):

        fund_quality[
            "Funds Below 85% Unconditional"
        ] = headline[
            "Funds Below 85% Unconditional"
        ]

    if (
        "Funds Below 85% Conditional"
        in headline
    ):

        fund_quality[
            "Funds Below 85% Conditional"
        ] = headline[
            "Funds Below 85% Conditional"
        ]

    summary[
        "fund_quality"
    ] = fund_quality


    # 5. Manager Quality
    manager_conditional = _load_csv(
        reports_dir /
        "data_state_by_manager_conditional.csv"
    )

    manager_base = _load_csv(
        reports_dir /
        "data_state_by_manager.csv"
    )

    manager_quality = {}

    if (
        manager_conditional is not None
        and manager_base is not None
    ):

        # Phase 1 excludes low-volume managers
        if "n_rows" in manager_base.columns:

            qualified = manager_base[
                manager_base[
                    "n_rows"
                ]
                >= 10
            ][
                "Investment Manager Allocator ID"
            ]

            manager_conditional = (
                manager_conditional[
                    manager_conditional[
                        "Investment Manager Allocator ID"
                    ]
                    .isin(qualified)
                ]
            )

        if "cond_completeness" in manager_conditional.columns:

            manager_quality[
                "Managers Scored"
            ] = len(
                manager_conditional
            )

            manager_quality[
                "Average Conditional Completeness"
            ] = _format_percent(
                manager_conditional[
                    "cond_completeness"
                ]
                .mean()
            )

            manager_quality[
                "Managers Below 85%"
            ] = int(
                (
                    manager_conditional[
                        "cond_completeness"
                    ]
                    < 0.85
                )
                .sum()
            )

    summary[
        "manager_quality"
    ] = manager_quality


    # 6. Consistency Assessment
    consistency = {}

    consistency_df = _load_csv(
        reports_dir /
        "consistency_rule_results.csv"
    )

    if consistency_df is not None:

        consistency[
            "Rules Evaluated"
        ] = len(
            consistency_df
        )

    deal_status_df = _load_csv(
        reports_dir /
        "deal_status_conformance_exceptions.csv"
    )

    if deal_status_df is not None:

        consistency[
            "Deal Status Exceptions"
        ] = len(
            deal_status_df
        )

    summary[
        "consistency"
    ] = consistency


    # 7. Data Hygiene
    excluded_df = _load_csv(
        reports_dir /
        "excluded_non_investment_rows.csv"
    )

    data_hygiene = {}

    if excluded_df is not None:

        data_hygiene[
            "Excluded Non-Investment Rows"
        ] = len(
            excluded_df
        )

    summary[
        "data_hygiene"
    ] = data_hygiene


    return summary